### PR TITLE
using koji plugin url from pagure

### PR DESCRIPTION
**Pull request by odra**
## Proposed Changes

* Changes the url of `fedmsg-koji-plugin.py` since the ansible repository was moved to pagure;

## Verification Steps

* Check if the new url is correct

## Additional Notes

Just a change of URLs since the old url was returning a 404 error.

### CODE REVIEW

**Review by Zlopez — APPROVED** [review]

**Comment by odra** [comment]
retest

**Comment by odra** [comment]
recheck

**Comment by odra** [comment]
recheck

**Comment by odra** [comment]
tests are failing because of a likely version issue of the python docker library used in local tests, I will address it in another pr since this is a image change only.

**Pull request merged**
