### PR TITLE
identity container and resources

### PR DESCRIPTION
**Pull request by odra**
## Changes

* Adds identity container source code in `images/identity`
* Adds a `kube.yaml` file to deploy it  it in kubernetes

### CODE REVIEW

**Comment by Zlopez** [comment]
Could you add at least one test, that will check if the identity is deployed and running.

**Comment by odra** [comment]
what do you mean by tests? we are not using it anywhere (yet).

**Comment by Zlopez** [comment]
Oh, in this case just ignore my comment.

**Comment by Zlopez** [comment]
recheck

**Pull request merged**
