### PR TITLE
Add new vagrant box for Operator SDK

### LINKED ISSUE #8: Setup Operator SDK development environment
If we want to use Operators, we should first create a development environment with Operator SDK. This will be rather difficult, because the Operator SDK needs Openshift 4.3+ as prerequisite and this is not packaged anywhere.

See this [guide](https://docs.openshift.com/container-platform/4.3/operators/operator_sdk/osdk-getting-started.html#osdk-installing-cli_osdk-getting-started) for more info.

### PR DESCRIPTION
**Pull request by Zlopez**
This commit adds preconfigured vagrant box with running minikube and
operator SDK.

Closes #8.

Signed-off-by: Michal Konečný <mkonecny@redhat.com>

### CODE REVIEW

**Comment by odra** [comment]
I ran into this error when executing `main.py`:

```
INFO:state:Ensuring component config
INFO:state:Ensuring component ca
INFO:state:Ensuring component fedmsg
INFO:state:Ensuring component database
INFO:state:Ensuring component koji_hub
INFO:state:Ensuring component client
INFO:state:Ensuring component koji_builder
Traceback (most recent call last):
  File "./main.py", line 52, in <module>
    main()
  File "./main.py", line 47, in main
    forced=args.force_update,
  File "/home/vagrant/devel/mbox/state.py", line 257, in ensure_all
    force_update=component in forced,
  File "/home/vagrant/devel/mbox/base.py", line 43, in ensure
    self.create()
  File "/home/vagrant/devel/mbox/koji_builder.py", line 25, in create
    "x86_64",
  File "/home/vagrant/devel/mbox/koji_hub.py", line 126, in ensure_builder_user
    res.check_returncode()
  File "/usr/lib64/python3.7/subprocess.py", line 444, in check_returncode
    self.stderr)
subprocess.CalledProcessError: Command '['oc', '-n', 'mbox', 'exec', 'client-1-rl289', '--', '/bin/bash', '-c', 'koji --config=/etc/client/koji.conf --profile=koji add-host koji-builder-built-in-1 x86_64']' returned non-zero exit status 1.
```

**Comment by Zlopez** [comment]
@odra Look at the logs in the pod `oc logs pod/client-1-rl289`, you could find more info there. But this one is problably not issue with the vagrant box, but probably something with the mbbox itself.
I recommend to delete `state` folder (this should be done after each run) and try to run it again. Probably recreate whole project as well.

I don't think we should try to solve these issues if we want to rewrite whole mbbox as operator anyway. This code will go away eventually.

**Comment by odra** [comment]
Agreed, the box and its components worked as expected but I can't approve the PR since I do not have the required permissions :)

**Comment by Zlopez** [comment]
We need to give you the permissions. Could you create a ticket on https://pagure.io/fedora-infrastructure/issues and request to be add to fedora-infra organization on GitHub?

**Comment by odra** [comment]
I think I already am as I do have access to the fasjson repository, do I need to be added in the mbox team (or something like that)?

I opened an issue anyway :)

**Comment by Zlopez** [comment]
@odra Could you now look at the #15?

**Comment by odra** [comment]
sure, will do

**Pull request merged**
