### PR TITLE
specific pip lib versions

### PR DESCRIPTION
**Pull request by odra**
## Proposed Changes

* specify all pip package versions

## Verification Steps

* ci job should work

### CODE REVIEW

**Comment by Zlopez** [comment]
I'm not sure if we want to freeze it like this.

**Comment by odra** [comment]
CI was not working because of a molecule/docker change, using latest sdk version would probably fix it but I don't have time for it right now, so  this is a temporary fix until I migrate it to the latest sdk structure.

**Comment by Zlopez** [comment]
In this case, could you add a comment that this is only temporary solution?

**Review by Zlopez — APPROVED** [review]

**Comment by Zlopez** [comment]
Just fix the failure and we are good to go.

**Comment by Zlopez** [comment]
.recheck

**Comment by Zlopez** [comment]
recheck

**Comment by Zlopez** [comment]
It was a temporary failure, so I think it's ready to merge

**Pull request merged**
